# Generated by Django 5.1.3 on 2024-12-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='fotos',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/fotos/'),
        ),
    ]
